#!/usr/bin/env python

import argparse as ap
import math

MSECONDS_IN_DAY = 86400000

if __name__ == '__main__':
    parser = ap.ArgumentParser(description='Epoch time utility')
    parser.add_argument('--mhCPD', dest='M', action='store', default=0.0)
    parser.add_argument('--M', dest='M', action='store', default=0.0)
    parser.add_argument('--C', dest='C', action='store', default=0.0)
    parser.add_argument('--conv', dest='C', action='store', default=0.0)

    args = parser.parse_args()

    M = float(args.M)
    C = float(args.C)
    obj_val = (10+C/2) * (math.exp(M / 10) - 1) / ((math.exp(M / 10) + 1))
    print obj_val
